project:
  type: website
  output-dir: docs

website:
  title: "mysite"
  description: "Personal website of Yuping Shao"

  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: research.qmd
      - href: software.qmd
      - href: blog.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango
