---
title: "About"
---

I am currently PhD student at the VISLab at the Worcester Polytechnic Institute.

### Research Interests

- Visual Recognition
- Optimization
- Biomedical Data Science
- Real-Time Systems

### Education

<!-- ::: {.d-flex .justify-content-between} -->
<!-- ::: {} -->
<!-- **New York University**   -->
<!-- PhD in Political Methodology   -->
<!-- Advisors: Cyrus Samii, Neal Beck, Josh Tucker -->
<!-- ::: -->
<!-- ::: {.text-end} -->
<!-- New York, NY   -->
<!-- Granted May 2016 -->
<!-- ::: -->
<!-- ::: -->

<!-- - Dissertation: *Essays on Causal Inference and Machine Learning with Application to Nonprofits* -->

<!-- - Winner of 2015 Williams Award for Best Dissertation Proposal in Political Methodology from the Society of Political Methodology -->


::: {.d-flex .justify-content-between}
::: {}
**Georgia Institute of Technology**  
M.S. in Computer Science
specialization Interactive Intelligence

:::
::: {.text-end}
New York, NY  
Granted Dec 2017
:::
:::


::: {.d-flex .justify-content-between}
::: {}
**Colorado State University**  
B.S. in Electrical, Computer Engineering
:::
::: {.text-end}
Fort Collins, CO
Granted Aug 2008
:::
:::

### Experience

::: {.d-flex .justify-content-between}
::: {}
**Worcester Polytechnic Institute**  
:::
::: {.text-end}
Jan 2021 - present
:::
:::
*Teaching Assistant*

- Supervisor: Ziming Zhang

::: {.d-flex .justify-content-between}
::: {}

**Massachusetts General Hospital**  
:::
::: {.text-end}
Sept 2016 - Dec 2020
:::
:::
*Research Scientist*

- Part of Eytan Bakshy's Adaptive Experimentation team
- Developed statistical, machine learning and experimental methodology
- Ran adaptive and contextual field experiments with a variety of product teams
- Integrated advanced methodologies into a toolkit for scalable and automatic experimentation intended for optimization ([Ax](https://ax.dev/)) - [released at F8 2019](https://developers.facebook.com/videos/2019/product-optimization-with-adaptive-experimentation/))
- Developed scalable methods for robust observational causal inference as the technical lead of our "CausalML" initiative

::: {.d-flex .justify-content-between}
::: {}
**Princeton University**  
:::
::: {.text-end}
September 2015 - May 2016
:::
:::
*Pre-doctoral fellow*

- Supervised by Kosuke Imai

::: {.d-flex .justify-content-between}
::: {}
**Facebook Core Data Science**  
:::
::: {.text-end}
Summer 2015
:::
:::
*Summer Intern*

- Statistical and Decision Science Team
- Supervised by Eytan Bakshy

### Teaching

#### Facebook
::: {.d-flex .justify-content-between}
::: {}
Internal datacamp class on designing and analyzing experiments 
:::
::: {.text-end}
2017-2019
:::
:::

#### NYU Undergraduate
::: {.d-flex .justify-content-between}
::: {}
TA for Power and Politics in America (under Jonathan Nagler)
:::
::: {.text-end}
Fall 2014
:::
:::

::: {.d-flex .justify-content-between}
::: {}
TA for Games, Strategy and Politics (under Steven Brams)
:::
::: {.text-end}
Fall 2013
:::
:::

#### NYU Graduate

::: {.d-flex .justify-content-between}
::: {}
TA for Quantitative Methods II (under Nathaniel Beck)
:::
::: {.text-end}
Spring 2015
:::
:::

::: {.d-flex .justify-content-between}
::: {}
TA for Quantitative Methods II (under Cyrus Samii)
:::
::: {.text-end}
Spring 2014
:::
:::

::: {.d-flex .justify-content-between}
::: {}
High Performance Computing Talk for NYU Datalab
:::
::: {.text-end}
February 2014
:::
:::

::: {.d-flex .justify-content-between}
::: {}
Introduction to R for NYU Datalab
:::
::: {.text-end}
January 2013
:::
:::